// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
      console.error(`[Supabase] ${message}`);
      throw new Response(message, { status: 500 });
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Response("Unauthorized: No request headers available", { status: 401 });
    }

    // Supabase token may arrive via Authorization header.
    // Some runtimes/frameworks can use different casing, so check both.
    const authHeader = request.headers.get("authorization") ?? request.headers.get("Authorization");

    let token: string | null = null;
    if (authHeader) {
      if (!authHeader.startsWith("Bearer ")) {
        throw new Response("Unauthorized: Only Bearer tokens are supported", { status: 401 });
      }
      token = authHeader.replace("Bearer ", "");
    }

    // Fallback: if token header missing, try to use Supabase session cookies.
    // This allows authenticated navigation flows to work even when the bearer header isn't forwarded.
    if (!token) {
      const supabaseForSession = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
        auth: {
          storage: undefined,
          persistSession: true,
          autoRefreshToken: false,
        },
      });

      const { data: sessionData, error: sessionErr } = await supabaseForSession.auth.getSession();
      if (sessionErr) {
        throw new Response(`Unauthorized: Failed to read session (${sessionErr.message})`, {
          status: 401,
        });
      }

      token = sessionData.session?.access_token ?? null;
      if (!token) {
        throw new Response(
          "Unauthorized: Missing Authorization header and no active Supabase session",
          {
            status: 401,
          },
        );
      }
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Response("Unauthorized: Invalid token", { status: 401 });
    }

    if (!data.claims.sub) {
      throw new Response("Unauthorized: No user ID found in token", { status: 401 });
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
