/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as AuthenticatedTelegramSetupRouteImport } from './routes/_authenticated/telegram-setup'
import { Route as AuthenticatedTelegramButtonsRouteImport } from './routes/_authenticated/telegram-buttons'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSchedulesRouteImport } from './routes/_authenticated/schedules'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedActivityLogsRouteImport } from './routes/_authenticated/activity-logs'
import { Route as AuthenticatedPostsNewRouteImport } from './routes/_authenticated/posts.new'
import { Route as ApiPublicHooksRunSchedulesRouteImport } from './routes/api/public/hooks/run-schedules'
import { Route as AuthenticatedPostsPostIdEditRouteImport } from './routes/_authenticated/posts.$postId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTelegramSetupRoute =
  AuthenticatedTelegramSetupRouteImport.update({
    id: '/telegram-setup',
    path: '/telegram-setup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTelegramButtonsRoute =
  AuthenticatedTelegramButtonsRouteImport.update({
    id: '/telegram-buttons',
    path: '/telegram-buttons',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSchedulesRoute = AuthenticatedSchedulesRouteImport.update({
  id: '/schedules',
  path: '/schedules',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedActivityLogsRoute =
  AuthenticatedActivityLogsRouteImport.update({
    id: '/activity-logs',
    path: '/activity-logs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPostsNewRoute = AuthenticatedPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHooksRunSchedulesRoute =
  ApiPublicHooksRunSchedulesRouteImport.update({
    id: '/api/public/hooks/run-schedules',
    path: '/api/public/hooks/run-schedules',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPostsPostIdEditRoute =
  AuthenticatedPostsPostIdEditRouteImport.update({
    id: '/posts/$postId/edit',
    path: '/posts/$postId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/telegram-buttons': typeof AuthenticatedTelegramButtonsRoute
  '/telegram-setup': typeof AuthenticatedTelegramSetupRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/schedules': typeof AuthenticatedSchedulesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/telegram-buttons': typeof AuthenticatedTelegramButtonsRoute
  '/telegram-setup': typeof AuthenticatedTelegramSetupRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/users': typeof AuthenticatedUsersRoute
  '/posts/new': typeof AuthenticatedPostsNewRoute
  '/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/activity-logs': typeof AuthenticatedActivityLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/schedules': typeof AuthenticatedSchedulesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/telegram-buttons': typeof AuthenticatedTelegramButtonsRoute
  '/_authenticated/telegram-setup': typeof AuthenticatedTelegramSetupRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/posts/new': typeof AuthenticatedPostsNewRoute
  '/_authenticated/posts/$postId/edit': typeof AuthenticatedPostsPostIdEditRoute
  '/api/public/hooks/run-schedules': typeof ApiPublicHooksRunSchedulesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/activity-logs'
    | '/dashboard'
    | '/history'
    | '/schedules'
    | '/settings'
    | '/telegram-buttons'
    | '/telegram-setup'
    | '/trash'
    | '/users'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/api/public/hooks/run-schedules'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/activity-logs'
    | '/dashboard'
    | '/history'
    | '/schedules'
    | '/settings'
    | '/telegram-buttons'
    | '/telegram-setup'
    | '/trash'
    | '/users'
    | '/posts/new'
    | '/posts/$postId/edit'
    | '/api/public/hooks/run-schedules'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/activity-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/schedules'
    | '/_authenticated/settings'
    | '/_authenticated/telegram-buttons'
    | '/_authenticated/telegram-setup'
    | '/_authenticated/trash'
    | '/_authenticated/users'
    | '/_authenticated/posts/new'
    | '/_authenticated/posts/$postId/edit'
    | '/api/public/hooks/run-schedules'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicHooksRunSchedulesRoute: typeof ApiPublicHooksRunSchedulesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telegram-setup': {
      id: '/_authenticated/telegram-setup'
      path: '/telegram-setup'
      fullPath: '/telegram-setup'
      preLoaderRoute: typeof AuthenticatedTelegramSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/telegram-buttons': {
      id: '/_authenticated/telegram-buttons'
      path: '/telegram-buttons'
      fullPath: '/telegram-buttons'
      preLoaderRoute: typeof AuthenticatedTelegramButtonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedules': {
      id: '/_authenticated/schedules'
      path: '/schedules'
      fullPath: '/schedules'
      preLoaderRoute: typeof AuthenticatedSchedulesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activity-logs': {
      id: '/_authenticated/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AuthenticatedActivityLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/new': {
      id: '/_authenticated/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof AuthenticatedPostsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/run-schedules': {
      id: '/api/public/hooks/run-schedules'
      path: '/api/public/hooks/run-schedules'
      fullPath: '/api/public/hooks/run-schedules'
      preLoaderRoute: typeof ApiPublicHooksRunSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/posts/$postId/edit': {
      id: '/_authenticated/posts/$postId/edit'
      path: '/posts/$postId/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof AuthenticatedPostsPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivityLogsRoute: typeof AuthenticatedActivityLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSchedulesRoute: typeof AuthenticatedSchedulesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTelegramButtonsRoute: typeof AuthenticatedTelegramButtonsRoute
  AuthenticatedTelegramSetupRoute: typeof AuthenticatedTelegramSetupRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedPostsNewRoute: typeof AuthenticatedPostsNewRoute
  AuthenticatedPostsPostIdEditRoute: typeof AuthenticatedPostsPostIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivityLogsRoute: AuthenticatedActivityLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSchedulesRoute: AuthenticatedSchedulesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTelegramButtonsRoute: AuthenticatedTelegramButtonsRoute,
  AuthenticatedTelegramSetupRoute: AuthenticatedTelegramSetupRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedPostsNewRoute: AuthenticatedPostsNewRoute,
  AuthenticatedPostsPostIdEditRoute: AuthenticatedPostsPostIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicHooksRunSchedulesRoute: ApiPublicHooksRunSchedulesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
